# Generated by Django 4.2 on 2023-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chat_date_time_alter_chat_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_time',
            field=models.CharField(default='05:40 PM', max_length=100),
        ),
    ]
