# Generated by Django 4.2 on 2023-05-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_chat_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_time',
            field=models.CharField(default='05:46 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='receiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
