# Generated by Django 4.2 on 2023-05-07 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_test_second_alter_chat_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='date_time',
            field=models.CharField(default='06:04 PM', max_length=100),
        ),
    ]
