# Generated by Django 4.2 on 2023-05-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test_second_alter_chat_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date_time',
            field=models.CharField(default='06:10 PM', max_length=100),
        ),
    ]
